title: 专 利 小 快 报
description: 设计相关专利，来自 Apple 等公司

url: "https://hi-o-id.github.io"
baseurl: "/daily-p-report"
lang: "zh-CN"
timezone: "Asia/Shanghai"

google_analytics: "G-9QBC2W58K"

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives  # 归档插件

# 归档插件配置
jekyll-archives:
  enabled: 
    - year
    - month
    - categories  # ✅ 启用 Category 归档
  layout: archive
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    category: '/category/:name/'  # ✅ Category 归档 URL

# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: ""

# 分页（可选）
paginate: 10
paginate_path: "/page:num/"

# 排除文件
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
